### PR TITLE
include iosfwd instead iostream

### PR DESCRIPTION
**Pull request by Neargye**

### CODE REVIEW

**Comment by rollbear** [comment]
Did this work around the MSVC bug?

**Comment by Neargye** [comment]
No, just less depend on big iostream.
I still try to understand msvc error msg.

**Comment by rollbear** [comment]
Back from the conference.

I don't think I understand this change. You get a compilation error if you `#include "dry-comparisons.hpp"` without having included `<iostream>` before it, which does not seem like an improvement to me. Am I missing something?

**Comment by Neargye** [comment]
The case when you need to use output operator is not so frequent.
Most likely people want to include dry-comparisons and use like `state == any_of(S1, S2, S3)`, and they not need operator <<, but if iostream included they will get slow compilation.

**Comment by Neargye** [comment]
If really need an output operator, first include iostream then dry-comparisons.
```
#include <iostream>
#include "dry-comparisons.hpp"
```

**Comment by rollbear** [comment]
No, it is not about needing it. Just this program fails to compile:

```
// t.cpp
#include "dry-comparisons.hpp"
```

```
bf😱confuciusornis /tmp> /opt/clang-9/bin/clang++   -std=c++17 -I ~/develop/dry-comparisons t.cpp
In file included from t.cpp:1:
/home/bf/develop/dry-comparisons/dry-comparisons.hpp:68:12: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const char *')
        os << label << '{';
        ~~ ^  ~~~~~
```

```
bf😱confuciusornis /tmp> clang++-8   -std=c++17 -I ~/develop/dry-comparisons t.cpp
In file included from t.cpp:1:
/home/bf/develop/dry-comparisons/dry-comparisons.hpp:68:12: error: invalid operands to binary
      expression ('std::ostream' (aka 'basic_ostream<char>') and 'const char *')
        os << label << '{';
        ~~ ^  ~~~~~
```

```
bf😱confuciusornis /tmp> g++-9   -std=c++17 -I ~/develop/dry-comparisons t.cpp
In file included from t.cpp:1:
/home/bf/develop/dry-comparisons/dry-comparisons.hpp: In member function ‘std::ostream& rollbear::internal::logical_tuple<Ts>::print(const char*, std::ostream&) const’:
/home/bf/develop/dry-comparisons/dry-comparisons.hpp:68:12: error: no match for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘const char*’)
   68 |         os << label << '{';
      |         ~~ ^~ ~~~~~
      |         |     |
      |         |     const char*
      |         std::ostream {aka std::basic_ostream<char>}
```

I do note that MSVC does accept the code by default, but if you compile with `/permissive-` it too fails to compile with a similar error message.

**Comment by Neargye** [comment]
Now I see, I apologize, carried away by an attempt to start on Windows. (By the way, it turned out to restore part of the functionality.)

**Comment by Neargye** [comment]
now build ok https://wandbox.org/permlink/ZvdLvarIdXuUdlfq

**Comment by rollbear** [comment]
Sure, but `<string_view>` includes `<iostream>`, so you have not gained anything.

**Comment by Neargye** [comment]
String_view include iosfrd 
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/string_view

**Comment by rollbear** [comment]
Um, interesting. It pulls in about 50kLOC of headers, much of which is iostream stuff, but `<iostream>` itself pulls in 90kLOC of headers, so it is a noticeable saving. I like that. Thanks.

**Comment by Neargye** [comment]
I would be glad to meet in person in St. Petersburg. Maybe I will fix msvc by this time)

**Comment by Neargye** [comment]
Will try remove depend on string_view, maybe help more.

**Comment by rollbear** [comment]
Yeah, `<string_view>` is actually not needed, and the test program can (and should) include `"dry-comparisons.hpp"` before any other headers. I slightly modified your version like this:

```
    template <typename C>
    std::basic_ostream<C>& print(const char* label, std::basic_ostream<C>& os) const
    {
        os << label << '{';
        std::apply([&os](const auto& ... v) {
            int first = 1;
            ((os << &","[std::exchange(first,0)] << v),...);
        }, self());
        return os << '}';
    
```

Now `os` is a dependent name, so it all seems to work fine.

Thanks. This was a bit of an unexpected adventure. A good one.

Meet in St. Petersburg sounds good. Going to the conf?

**Comment by Neargye** [comment]
Maybe print(const C* label...)?

**Comment by Neargye** [comment]
Yes, planned go to conf.

**Comment by Neargye** [comment]
Becouse steam<wchar> can't print char uses <<.

**Comment by rollbear** [comment]
Yeah, `const C* label` would be better.

**Comment by Neargye** [comment]
Update PR.

**Comment by rollbear** [comment]
Super! Thanks.

**Pull request merged**
